version: "3.9"

############################
# 1) Ergo‑MCP  (API server)
############################
services:
  ergo-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ergo-mcp
    env_file: .env
    environment:
      ERGO_EXPLORER_API: ${ERGO_EXPLORER_API}
      ERGO_NODE_API:     ${ERGO_NODE_API}
      ERGO_NODE_API_KEY: ${ERGO_NODE_API_KEY}
      ERGOWATCH_API_URL: ${ERGOWATCH_API_URL}
      NETWORK:           ${NETWORK:-mainnet}
      PORT:              ${ERGO_MCP_PORT:-3002}
    ports:
      - "${ERGO_MCP_PORT:-3002}:${ERGO_MCP_PORT:-3002}"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

    # ---- HEALTH‑CHECK: succeed on *any* HTTP status ----
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:3002/ >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s   # safe window for initial EIP cache build

############################
# 2) MCP‑O (reverse‑proxy / auth)
############################
  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    container_name: ergo-mcpo
    depends_on:
      ergo-mcp:
        condition: service_healthy
    environment:
      MCPO_API_KEY: ${MCPO_API_KEY}
    command: >
      mcpo
      --host 0.0.0.0
      --port ${MCPO_PORT:-3003}
      --api-key ${MCPO_API_KEY}
      http://ergo-mcp:3002
    ports:
      - "${MCPO_PORT:-3003}:${MCPO_PORT:-3003}"
    restart: unless-stopped

############################
# Shared bridge network
############################
networks:
  default:
    name: ergo-network
    driver: bridge
